set(CORE_BUILD "${CMAKE_SOURCE_DIR}/build/Debug")
set(CORE_ISNTALL "${CMAKE_INSTALL_PREFIX}/bin")

# message(STATUS "BEFORE PERL SCRIPT EXECUTION:\n BINARY_DIR: ${CORE_BUILD}\n INSTALL_PREFIX: ${CORE_ISNTALL}")
execute_process(
    COMMAND perl ${CMAKE_CURRENT_SOURCE_DIR}/utils/core_copy_missing_dlls.pl
    ${CORE_BUILD}
    ${CORE_ISNTALL}
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE result
)

if(result EQUAL 0)
    message(STATUS "PERL SCRIPT EXECUTED SUCCESSFULLY.")
else()
    message(FATAL_ERROR "PERL SCRIPT FAILED.")
endif()