name: Windows x64 Debug

on: [push, pull_request]

jobs:
  Build-Windows-x64-Debug:
    runs-on: windows-latest
    container: durengo/vcpkg_core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up MSVC
      #   uses: TheMrMilchmann/setup-msvc-dev@v2.0.1
      #   with:
      #     arch: x64

      # - name: Set up CMake
      #   uses: jwlawson/actions-setup-cmake@v1.13
      #   with:
      #     cmake-version: "3.22"
      # - name: Test CMake
      #   run: cmake --version

      # - name: Install VCPKG
      #   run: |
      #     git clone https://github.com/Microsoft/vcpkg.git
      #     ./vcpkg/bootstrap-vcpkg.bat

      # - name: Install VCPKG packages
      #   run: |
      #     ./vcpkg/vcpkg.exe install fmt spdlog jsoncpp stb gtest --triplet x64-windows

      # - name: Install Perl
      #   uses: shogo82148/actions-setup-perl@v1
      #   with:
      #     perl-version: '5.38'
      # - run: cpanm --installdeps .
      # - run: prove -lv t

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.11'

      - name: cmake test
        run: cmake --version

      # - name: Configure and build the project
      #   run: |
      #     echo CONFIGURATION
      #     dir
      #     echo ./setup --no-deps-check
      #     ./setup.bat --no-deps-check
      #     echo ./build --clean-rebuild
      #     ./build --clean-rebuild

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build-artifacts
      #     path: |
      #       build
      #       Install
